{% set name = "aiocron" %}
{% set version = "2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiocron-{{ version }}.tar.gz
  sha256: 1bb65a36aee137e8833592783956e0c7dc478bc3e9273fc2841d5d0c6045e4d2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - cronsim >=2.6
    - python-dateutil >=2.9.0
    - tzlocal >=5.2

test:
  imports:
    - aiocron
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gawel/aiocron/
  summary: Crontabs for asyncio
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
