{% set name = "aiocron" %}
{% set version = "1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiocron-{{ version }}.tar.gz
  sha256: 48546513faf2eb7901e65a64eba7b653c80106ed00ed9ca3419c3d10b6555a01

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - croniter
    - tzlocal

test:
  imports:
    - aiocron
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gawel/aiocron/
  summary: Crontabs for asyncio
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
